SELECT * FROM Lego.part_categories;

INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('1', 'Baseplates');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('2', 'Bricks Printed');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('3', 'Bricks Sloped');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('4', 'Duplo, Quatro and Primo');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('5', 'Bricks Special');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('6', 'Bricks Wedged');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('7', 'Containers');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('8', 'Technic Bricks');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('9', 'Plates Special');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('10', 'Tiles Printed');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('11', 'Bricks');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('12', 'Technic Connectors');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('13', 'Minifigs');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('14', 'Plates');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('15', 'Tiles Special');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('16', 'Windows and Doors');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('17', 'Non-LEGO');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('18', 'Hinges, Arms and Turntables');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('19', 'Tiles');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('20', 'Bricks Round and Cones');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('21', 'Plates Round and Dishes');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('22', 'Pneumatics');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('23', 'Panels');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('24', 'Other');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('25', 'Technic Steering, Suspension and Engine');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('26', 'Technic Special');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('27', 'Minifig Accessories');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('28', 'Plants and Animals');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('29', 'Wheels and Tyres');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('30', 'Tubes and Hoses');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('31', 'String, Bands and Reels');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('32', 'Bars, Ladders and Fences');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('33', 'Rock');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('34', 'Supports, Girders and Cranes');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('35', 'Transportation - Sea and Air');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('36', 'Transportation - Land');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('37', 'Bricks Curved');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('38', 'Flags, Signs, Plastics and Cloth');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('39', 'Magnets and Holders');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('40', 'Technic Panels');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('41', 'Bionicle, Hero Factory and Constraction');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('42', 'Belville, Scala and Fabuland');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('43', 'Znap');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('44', 'Mechanical');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('45', 'Power Functions, Mindstorms and Electric');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('46', 'Technic Axles');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('47', 'Windscreens and Fuselage');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('48', 'Clikits');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('49', 'Plates Angled');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('50', 'HO Scale');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('51', 'Technic Beams');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('52', 'Technic Gears');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('53', 'Technic Pins');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('54', 'Technic Bushes');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('55', 'Technic Beams Special');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('56', 'Tools');
INSERT INTO `Lego`.`part_categories` (`id`, `name`) VALUES ('57', 'Non-Buildable Figures (Duplo, Fabuland, etc)');
