SELECT * FROM Lego.themes;

INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('1', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('2', 'Arctic Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('3', 'Competition');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('4', 'Expert Builder');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('5', 'Model');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('6', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('7', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('8', 'Farm');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('9', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('10', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('11', 'Off-Road');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('12', 'Race');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('13', 'Riding Cycle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('14', 'Robot');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('15', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('16', 'RoboRiders');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('17', 'Speed Slammers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('18', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('19', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('20', 'Throwbot Slizer');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('21', 'Universal Building Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('22', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('23', 'Basic Model');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('24', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('25', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('26', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('27', 'Race');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('28', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('29', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('30', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('31', 'Creature');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('32', 'Robot');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('33', 'Food & Drink');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('34', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('35', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('36', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('37', 'Basic Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('38', 'Model');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('39', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('40', 'Creature');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('41', 'Riding Cycle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('42', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('43', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('44', 'Recreation');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('45', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('46', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('47', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('48', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('49', 'Mecha');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('50', 'Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('51', 'Arctic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('52', 'City');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('53', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('54', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('55', 'Coast Guard');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('56', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('57', 'Farm');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('58', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('59', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('60', 'Hospital');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('61', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('62', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('63', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('64', 'Off-Road');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('65', 'Arctic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('66', 'Trains');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('67', 'Classic Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('68', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('69', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('70', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('71', 'Coast Guard');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('72', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('73', 'Farm');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('74', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('75', 'Food & Drink');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('76', 'Station');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('77', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('78', 'Hospital');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('79', 'Off-Road');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('80', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('81', 'Post Office');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('82', 'Race');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('83', 'Recreation');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('84', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('85', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('86', 'Divers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('87', 'Extreme Team');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('88', 'Launch Command');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('89', 'Outback');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('90', 'Paradisa');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('91', 'Race');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('92', 'Res-Q');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('93', 'Space Port');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('94', 'Town Jr.');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('95', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('96', 'Coast Guard');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('97', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('98', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('99', 'Gas Station');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('100', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('101', 'Race');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('102', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('103', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('104', 'Town Plan');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('105', 'World City');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('106', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('107', 'Coast Guard');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('108', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('109', 'Food & Drink');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('110', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('111', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('112', 'Racers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('113', 'Drome Racers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('114', 'Ferrari');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('115', 'Lamborghini');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('116', 'Power Racers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('117', 'Radio Control');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('118', 'Speed Racer');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('119', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('120', 'Tiny Turbos');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('121', 'Track System');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('122', 'Williams F1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('123', 'World Racers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('124', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('125', 'Xalax');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('126', 'Space');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('127', 'Alien Conquest');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('128', 'Blacktron I');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('129', 'Blacktron II');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('130', 'Classic Space');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('131', 'Exploriens');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('132', 'Futuron');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('133', 'Ice Planet 2002');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('134', 'Insectoids');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('135', 'Life On Mars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('136', 'M:Tron');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('137', 'Mars Mission');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('138', 'RoboForce');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('139', 'Space Police I');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('140', 'Space Police II');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('141', 'Space Police III');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('142', 'Spyrius');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('143', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('144', 'UFO');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('145', 'Unitron');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('146', 'Galaxy Squad');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('147', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('148', 'Pirates I');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('149', 'Imperial Armada');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('150', 'Imperial Guards');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('151', 'Imperial Soldiers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('152', 'Islanders');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('153', 'Pirates II');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('154', 'Pirates III');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('155', 'Modular Buildings');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('156', 'Mini');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('157', 'Bricktober');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('158', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('159', 'Mini');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('160', 'Star Wars Clone Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('161', 'Star Wars Episode 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('162', 'Star Wars Episode 3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('163', 'Star Wars Episode 4/5/6');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('164', 'Star Wars Episode 1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('165', 'Star Wars Clone Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('166', 'Star Wars Episode 1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('167', 'Star Wars Episode 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('168', 'Star Wars Episode 3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('169', 'Star Wars Episode 4/5/6');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('170', 'Star Wars Other');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('171', 'Ultimate Collector Series');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('172', 'Star Wars Episode 1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('173', 'Star Wars Episode 3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('174', 'Star Wars Episode 4/5/6');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('175', 'Star Wars Episode 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('176', 'Planet Series 1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('177', 'Planet Series 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('178', 'Minifig Pack');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('179', 'Planet Series 3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('180', 'Planet Series 4');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('181', 'Star Wars Episode 4/5/6');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('182', 'Star Wars Rebels');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('183', 'Star Wars Expanded Universe');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('184', 'Star Wars Episode 7');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('185', 'Star Wars Rogue One');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('186', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('187', 'Black Falcons');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('188', 'Black Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('189', 'Classic Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('190', 'Crusaders');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('191', 'Dark Forest');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('192', 'Dragon Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('193', 'Fantasy Era');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('194', 'Forestmen');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('195', 'Fright Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('196', 'Kingdoms');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('197', 'Knights Kingdom I');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('198', 'Knights Kingdom II');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('199', 'Lion Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('200', 'My Own Creation');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('201', 'Royal Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('202', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('203', 'Wolfpack');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('204', 'Designer Sets');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('205', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('206', 'Seasonal');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('207', 'Advent');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('208', 'City');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('209', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('210', 'Belville');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('211', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('212', 'Classic Basic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('213', 'Clikits');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('214', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('215', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('216', 'Friends');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('217', 'Advent Sub-Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('218', 'Belville');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('219', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('220', 'City');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('221', 'Classic Basic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('222', 'Clikits');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('223', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('224', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('225', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('226', 'Friends');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('227', 'Christmas');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('228', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('229', 'Easter');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('230', 'Halloween');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('231', 'Thanksgiving');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('232', 'Valentine');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('233', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('234', '12V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('235', '4.5V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('236', '9V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('237', 'My Own Creation');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('238', 'My Own Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('239', 'World City');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('240', 'RC Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('241', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('242', '12V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('243', '4.5V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('244', '9V');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('245', 'RC Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('246', 'Harry Potter');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('247', 'Chamber of Secrets');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('248', 'Goblet of Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('249', 'Order of the Phoenix');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('250', 'Prisoner of Azkaban');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('251', 'Sorcerer\'s Stone');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('252', 'Architecture');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('253', 'Skylines');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('254', 'Bulk Bricks');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('255', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('256', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('257', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('258', 'Mindstorms');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('259', 'NXT');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('260', 'RCX');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('261', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('262', 'EV3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('263', 'Pirates of the Caribbean');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('264', 'Indiana Jones');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('265', 'Kingdom of the Crystal Skull');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('266', 'Last Crusade');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('267', 'Raiders of the Lost Ark');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('268', 'Temple of Doom');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('269', 'Cars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('270', 'Ben 10');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('271', 'Prince of Persia');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('272', 'SpongeBob SquarePants');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('273', 'Studios');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('274', 'Jurassic Park III');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('275', 'Toy Story');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('276', 'Sculptures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('277', 'Mosaic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('278', 'Model Team');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('279', '4 Juniors');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('280', 'Jack Stone');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('281', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('282', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('283', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('284', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('285', 'Gas Station');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('286', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('287', 'Spider-Man');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('288', 'Spider-Man 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('289', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('290', 'Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('291', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('292', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('293', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('294', 'Gas Station');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('295', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('296', 'Adventurers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('297', 'Desert');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('298', 'Dino Island');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('299', 'Jungle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('300', 'Orient Expedition');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('301', 'Other');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('302', 'Agents');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('303', 'Ultra Agents');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('304', 'Alpha Team');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('305', 'Mission Deep Sea');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('306', 'Mission Deep Freeze');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('307', 'Aquazone');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('308', 'Aquanauts');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('309', 'Aquaraiders I');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('310', 'Aquaraiders II');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('311', 'Aquasharks');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('312', 'Hydronauts');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('313', 'Stingrays');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('314', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('315', 'Atlantis');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('316', 'Mini');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('317', 'Avatar');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('318', 'Belville');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('319', 'Fairy-Tale');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('320', 'Golden Land');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('321', 'Hospital');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('322', 'Playhouse');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('323', 'Recreation');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('324', 'Bionicle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('325', 'Agori');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('326', 'Barraki');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('327', 'Battle Vehicles');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('328', 'Bohrok');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('329', 'Bohrok Va');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('330', 'Bohrok-Kal');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('331', 'Glatorian');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('332', 'Glatorian Legends');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('333', 'Matoran of Light');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('334', 'Matoran of Mahri Nui');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('335', 'Matoran of Mata Nui');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('336', 'Matoran of Metru Nui');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('337', 'Matoran of Voya Nui');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('338', 'Mistika');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('339', 'Phantoka');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('340', 'Piraka');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('341', 'Playsets');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('342', 'Rahaga');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('343', 'Rahi');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('344', 'Rahkshi');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('345', 'Stars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('346', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('347', 'Titans');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('348', 'Toa');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('349', 'Toa Hagah');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('350', 'Toa Hordika');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('351', 'Toa Inika');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('352', 'Toa Mahri');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('353', 'Toa Metru');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('354', 'Toa Nuva');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('355', 'Tohunga');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('356', 'Turaga');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('357', 'Vahki');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('358', 'Visorak');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('359', 'Warriors');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('360', 'Protectors');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('361', 'Skull Spiders');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('362', 'Toa Okoto');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('363', 'Boat');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('364', 'Building Set with People');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('365', 'Classic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('366', 'Basic Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('367', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('368', 'HO 1:87 Vehicles');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('369', 'Jumbo Bricks');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('370', 'Mosaic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('371', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('372', 'Town Plan');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('373', 'Vehicle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('374', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('375', 'Farm');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('376', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('377', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('378', 'Traffic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('379', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('380', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('381', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('382', 'Cargo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('383', 'Wooden Box Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('384', 'Dino 2010');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('385', 'Dino Attack');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('386', 'Dinosaurs');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('387', 'Discovery');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('388', 'Disney\'s Mickey Mouse');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('389', 'Exo-Force');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('390', 'Fabuland');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('391', 'Hospital');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('392', 'Post Office');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('393', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('394', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('395', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('396', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('397', 'Factory');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('398', 'FIRST LEGO League');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('399', 'Freestyle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('400', 'Hero Factory');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('401', 'Heroes');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('402', 'Vehicles');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('403', 'Villains');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('404', 'Hobby Sets');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('405', 'Homemaker');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('406', 'Inventor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('407', 'Island Xtreme Stunts');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('408', 'LEGO Brand Store');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('409', 'Monthly Mini Model Build');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('410', 'Pick A Model');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('411', 'Legoland');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('412', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('413', 'Building');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('414', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('415', 'Coast Guard');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('416', 'Construction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('417', 'Fire');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('418', 'Gas Station');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('419', 'Harbor');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('420', 'Hospital');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('421', 'Police');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('422', 'Space');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('423', 'Vehicle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('424', 'Western');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('425', 'Legoland Parks');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('426', 'Bionicle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('427', 'Holiday');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('428', 'Christmas');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('429', 'Halloween');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('430', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('431', 'Star Wars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('432', 'Master Building Academy');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('433', 'Minitalia');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('434', 'Ninja');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('435', 'Ninjago');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('436', 'Airjitzu');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('437', 'Pharaoh\'s Quest');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('438', 'Power Functions');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('439', 'Power Miners');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('440', 'Primo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('441', 'Quatro');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('442', 'Rock Raiders');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('443', 'Service Packs');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('444', 'Adventurers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('445', 'Aquazone');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('446', 'Belville');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('447', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('448', 'Fabuland');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('449', 'Pirates');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('450', 'Primo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('451', 'Scala');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('452', 'Space');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('453', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('454', 'Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('455', 'Classic Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('456', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('457', 'Western ');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('458', 'Sports');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('459', 'Basketball');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('460', 'Gravity Games');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('461', 'Hockey');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('462', 'Soccer');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('463', 'Spybiotics');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('464', 'Time Cruisers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('465', 'Universal Building Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('466', 'Airport');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('467', 'Basic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('468', 'Basic Model');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('469', 'Basic Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('470', 'Classic Basic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('471', 'Ferries');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('472', 'Gears');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('473', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('474', 'Vikings');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('475', 'Western');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('476', 'Cowboys');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('477', 'Indians');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('478', 'X-Pod');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('479', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('480', 'Znap');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('481', 'Dino');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('482', 'Super Heroes');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('483', 'Guardians of the Galaxy');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('484', 'Batman');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('485', 'Ultimate Collector Series');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('486', 'Justice League');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('487', 'Avengers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('488', 'Spider-Man');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('489', 'Superman');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('490', 'Iron Man');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('491', 'X-Men');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('492', 'Constraction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('493', 'Marvel');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('494', 'Friends');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('495', 'Jungle Rescue');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('496', 'Animals');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('497', 'Books');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('498', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('499', 'Train');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('500', 'Clikits');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('501', 'Gear');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('502', 'Game');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('503', 'Key Chain');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('504', 'Duplo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('505', 'Basic Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('506', 'Cars');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('507', 'Educational and Dacta');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('508', '4 Juniors');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('509', 'Adventurers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('510', 'Boat');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('511', 'Building Set with People');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('512', 'Castle');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('513', 'Classic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('514', 'Creator');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('515', 'Dinosaurs');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('516', 'Explore');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('517', 'Learning');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('518', 'Mindstorms');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('519', 'NXT');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('520', 'RCX');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('521', 'WeDo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('522', 'Primo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('523', 'Samsonite');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('524', 'Service Packs');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('525', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('526', 'Soft Bricks');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('527', 'Space');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('528', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('529', 'Technic');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('530', 'Control Lab');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('531', 'eLAB');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('532', 'Supplemental');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('533', 'Town');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('534', 'Universal Building Set');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('535', 'Collectible Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('536', 'Series 1 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('537', 'Series 2 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('538', 'Series 3 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('539', 'Series 4 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('540', 'Series 5 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('541', 'Series 6 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('542', 'Series 7 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('543', 'Series 8 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('544', 'Series 9 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('545', 'Series 10 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('546', 'Team GB');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('547', 'Series 11 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('548', 'Series 12 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('549', 'The LEGO Movie Series');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('550', 'The Simpsons');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('551', 'Series 13 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('552', 'Series 14 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('553', 'The Simpsons Series 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('554', 'Series 15 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('555', 'Disney');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('556', 'Series 16 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('557', 'DFB Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('558', 'Monster Fighters');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('559', 'Value Packs');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('560', 'Universe');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('561', 'The Hobbit and Lord of the Rings');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('562', 'The Hobbit');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('563', 'An Unexpected Journey');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('564', 'The Desolation of Smaug');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('565', 'The Battle of the Five Armies');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('566', 'The Lord of the Rings');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('567', 'The Fellowship of the Ring');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('568', 'The Two Towers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('569', 'The Return of the King');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('570', 'Teenage Mutant Ninja Turtles');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('571', 'Legends of Chima');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('572', 'Speedorz');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('573', 'Constraction');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('574', 'Legend Beasts');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('575', 'The Lone Ranger');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('576', 'LEGO Ideas and CUUSOO');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('577', 'Minecraft');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('578', 'The LEGO Movie');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('579', 'Disney Princess');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('580', 'Mixels');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('581', 'Series 1');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('582', 'Series 2');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('583', 'Series 3');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('584', 'Series 4');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('585', 'Series 5');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('586', 'Series 6');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('587', 'Series 7');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('588', 'Series 8');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('589', 'Series 9');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('590', 'Fusion');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('591', 'Juniors');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('592', 'DC Comics Super Heroes');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('593', 'Disney Princess');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('594', 'Fantasy');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('595', 'Friends');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('596', 'Marvel Super Heroes');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('597', 'Nijago');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('598', 'Promotional');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('599', 'LEGO Exclusive');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('600', 'Elves');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('601', 'Speed Champions');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('602', 'Jurassic World');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('603', 'Scooby-Doo');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('604', 'Dimensions');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('605', 'Nexo Knights');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('606', 'Angry Birds');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('607', 'Ghostbusters');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('608', 'Disney');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('609', 'The LEGO Batman Movie');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('610', 'Brickheadz');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('611', 'Series 17 Minifigures');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('612', 'Star Wars Episode 8');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('613', 'Freemakers');
INSERT INTO `Lego`.`themes` (`id`, `name`) VALUES ('614', 'Jungle');
